# Generated by Django 3.2.4 on 2021-07-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=240)),
                ('brand', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('veh_id', models.AutoField(primary_key=True, serialize=False)),
                ('km', models.PositiveIntegerField(help_text='Enter field documentation')),
                ('plaka', models.CharField(help_text='Enter field documentation', max_length=240)),
                ('sase_numarasi', models.IntegerField(help_text='Enter field documentation')),
                ('renk', models.CharField(choices=[('WHITE', 'white'), ('GREEN', 'green'), ('YELLOW', 'yellow'), ('BLACK', 'black')], default='WHITE', max_length=6)),
                ('vehicle_model', models.ManyToManyField(to='vehicle.VehicleModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
